repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.2.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
