---

- name: "remove {{ item.name }} sudoer"
  file:
    path: "{{ config_prefix }}/sudoers.d/{{ item.name }}"
    state: absent

- name: "remove {{ item.name }} user"
  user:
    name: "{{ item.name }}"
    remove: true
    state: absent

- name: "remove {{ item.name }} group"
  group:
    name: "{{ item.name }}"
    state: absent
