---

- name: "remove {{ item.name }} sudoer"
  ansible.builtin.file:
    path: "{{ config_prefix }}/sudoers.d/{{ item.name }}"
    state: absent

- name: "remove {{ item.name }} user"
  ansible.builtin.user:
    name: "{{ item.name }}"
    remove: true
    state: absent

- name: "remove {{ item.name }} group"
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: absent
