---

- name: install sudo package
  ansible.builtin.package:
    name: sudo
    state: present

- name: Setup sudoers.d
  ansible.builtin.lineinfile:
    dest: "{{ config_prefix }}/sudoers"
    line: "#includedir /etc/sudoers.d"
    regexp: "^#includedir /etc/sudoers.d"
    validate: "visudo -cf %s"
    state: present

- name: install zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: install zsh
  ansible.builtin.command:
    cmd: which zsh
  register: which_zsh
  changed_when: false

- name: collect uids
  ansible.builtin.command: "awk -F : '{print $3}' /etc/passwd"
  register: uids
  changed_when: false

- name: collect gids
  ansible.builtin.command: "awk -F : '{print $3}' /etc/group"
  register: gids
  changed_when: false

- name: collect groups
  ansible.builtin.command: "awk -F : '{print $1}' /etc/group"
  register: group_names
  changed_when: false

- name: exclude users
  ansible.builtin.set_fact:
    sfup_users: "{{ sfup_users |rejectattr('name', 'in', exclude ) }}"

- name: setup users
  ansible.builtin.include_tasks: present_user.yml
  when: (item.state | default('present')) == 'present'
  with_items: "{{ sfup_users + additional_users }}"

- name: remove users
  ansible.builtin.include_tasks: absent_user.yml
  when: (item.state | default('present')) == 'absent'
  with_items: "{{ sfup_users + additional_users }}"
